#!/bin/sh
set -e

# Xcode Cloud runs this after `git clone`. The repo intentionally ignores
# Grove.xcodeproj and Secrets.xcconfig. We materialize both here so the
# build has everything it needs.
#
# Required Xcode Cloud environment variables (set them in the workflow's
# Environment tab, marked Secret):
#   BRAPI_TOKEN
#   MOBILE_API_KEY

cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "==> Writing Secrets.xcconfig from environment"
if [ -z "$BRAPI_TOKEN" ] || [ -z "$MOBILE_API_KEY" ]; then
  echo "ERROR: BRAPI_TOKEN and MOBILE_API_KEY must be set as Xcode Cloud environment variables."
  exit 1
fi
cat > Secrets.xcconfig <<EOF
// Generated by ci_post_clone.sh — do not edit.
BRAPI_TOKEN = ${BRAPI_TOKEN}
MOBILE_API_KEY = ${MOBILE_API_KEY}
EOF

echo "==> Installing XcodeGen"
brew install xcodegen

echo "==> Generating Grove.xcodeproj from project.yml"
xcodegen generate
